"""add tag

Revision ID: 7f02356c301e
Revises: d76c8712ed74
Create Date: 2023-03-21 11:49:27.470360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f02356c301e"
down_revision = "d76c8712ed74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_model", sa.Column("tag", sa.String(length=254), nullable=True))
    op.alter_column(
        "user_model", "email", existing_type=sa.VARCHAR(length=254), nullable=True
    )
    op.create_index(op.f("ix_user_model_tag"), "user_model", ["tag"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_model_tag"), table_name="user_model")
    op.alter_column(
        "user_model", "email", existing_type=sa.VARCHAR(length=254), nullable=False
    )
    op.drop_column("user_model", "tag")
    # ### end Alembic commands ###
